### ISSUE TITLE
Title Tag

### ISSUE THREAD

**Issue by matysek** [openlyrics/openlyrics#14]
<a href="https://github.com/GoogleCodeExporter"><img src="https://avatars.githubusercontent.com/u/9614759?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [GoogleCodeExporter](https://github.com/GoogleCodeExporter)**
_Sunday Mar 29, 2015 at 21:00 GMT_
_Originally opened as https://github.com/matysek/openlyrics/issues/14_

---

```
The title's "translit" property is not documented as an option under the 
"Title" section.

Also, the "original" attribute is not available in the python library. 
"translit" is not in the old library.
```

Original issue reported on code.google.com by `bradleelandis` on 1 Mar 2011 at 10:04

Tasks (@gyuris):
- [x] Document optional `translit` attribute alongside `lang` attribute for `<title>`.
- [x] Document optional `translit` attribute alongside `lang` attribute for `<theme>`.
- 3rd case is documented: `<verse>`
- [x] Create reference implementation for  `translit` with `<title>` and `<theme>`: XSL

**Comment by matysek** [comment]
<a href="https://github.com/GoogleCodeExporter"><img src="https://avatars.githubusercontent.com/u/9614759?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [GoogleCodeExporter](https://github.com/GoogleCodeExporter)**
_Sunday Mar 29, 2015 at 21:00 GMT_

----



Original comment by `mzibri...@gmail.com` on 23 Jul 2011 at 3:24
* Added labels: **Milestone-0.8**, **Type-Task**
* Removed labels: **Type-Defect**

**Comment by gyuris** [comment]
Task:
- [ ] Document optional `translit` attribute alongside `lang` attribute for `<title>`.
- [ ] Document optional `translit` attribute alongside `lang` attribute for `<theme>`.
- 3rd case is documented: `<verse>`

**Comment by gyuris** [comment]
I consider unfinished python library deprecated.
