### ISSUE TITLE
Single source project manifesto

### ISSUE THREAD

**Issue by gyuris** [openlyrics/openlyrics#29]
# Objective

Use single [OpenLyrics](http://openlyrics.info/) files as the source of various kinds of outputs (e.g. printed song books, projected e.g. with OpenLP, etc.), each with multiple display options (single source publishing).
# Details

Regarding printed outputs we have the following goals:
I. Use a single source to generate three different versions:
1. words only
2. words with chords as it is usual, optimized for a single guitar
3. orchestral, containing words with chords and all necessary introduction, intermezzo, and conclusion parts

II. Display the OpenLyrics XML file using native CSS(+XSLT?) and use XML(+XSLT?)+CSS to generate PDF output.

To test our concepts and implementation, first we plan to adapt the song book hosted at http://enekfuzet.ujevangelizacio.hu/ to use the described technology. Next, the whole Hungarian Christian OpenLyrics database called [Ászáf](https://github.com/gyuris/aszaf) would be converted.
## Developments planned
- Add support to the OpenLyrics standard (through the modification of the RELAX NG schema) for:
  - Semantic chord notation: chords written onto words, problems originating from congestion of words or chords, upbeats, line ending chords (without words).
  - New verse types for intro, middle, and outro parts; bar, rest.
  - Necessary semantic improvements: repeating lines.
- Documentation of new features (with examples).
- Sample implementation of a CSS based OpenLyrics viewer.
# Misc
- Developers:
  - [Tamás Riszterer](https://github.com/triszterer)
  - [Attila Tóth](https://github.com/atmenta)
  - [Gellért Gyuris](https://github.com/gyuris)
- Mentor: [Martin Zibricky](https://github.com/matysek)
- Development branch: [single-source](https://github.com/openlyrics/openlyrics/tree/single-source)
# Final thoughts

We do not think that these developments per se should be considered as OpenLyrics version 0.9. Among the boundaries of this project we do not intend to deal with any other topics than those described above. I.e. we do not intend to deal with other questions, suggestions or issues emerged in the [Google group of the project](http://groups.google.com/group/openlyrics) or in the [issue tracker](https://github.com/openlyrics/openlyrics/issues). We simply do not feel ourselves competent to judge what should or should not be included in the OpenLyrics standard. We hope that if we succeed, others will become motivated to implement further features.

**Comment by matysek** [comment]
Looks great.

**Comment by gyuris** [comment]
Prototype features: https://github.com/gyuris/openlyrics-prototype
