### ISSUE TITLE
Add new author type "Altered by"

### ISSUE THREAD

**Issue by smehrbrodt** [openlyrics/openlyrics#39]
Requested here: https://bugs.launchpad.net/openlp/+bug/1546530

**Comment by gyuris** [comment]
OK, lets standardise this author type. "Altered by" is a good label for OpenLP, but it doesn't fit other types. Other author types are currently:
- `words` 
- `music`
- `translation` (+language)

They answers the question: What this author produced? So I suggest: `alteration`, `variant`, `revision`...

We have currently a `<variant>` tag in metadata, [see in documentation](https://docs.openlyrics.org/en/latest/dataformat.html#variant). It suggest `variant`. It would be clear that if a song has a variant that we can assign an author with variant type:

```
<variant>Newsboys</variant>
<authors>
  <author type="words">XY</author>
  <author type="music">XY</author>
  <author type="variant">Michael Tait</author>
</authors>
```
