### ISSUE TITLE
openlyrics.org says: "This account has been suspended."

### ISSUE THREAD

**Issue by gyuris** [openlyrics/openlyrics#40]
- Visit http://openlyrics.org domain.
- I got "Account Suspended" page.

Who is responsible for the domain?

**Comment by rsnyman** [comment]
Hey @gyuris thanks for alerting us. I've redirected the domain back to GitHub. It should take effect over the 24 hours.

**Comment by gyuris** [comment]
Raoul, good to see you here. Thanks for redirecting the domain.

Now points [here](https://github.com/openlyrics/openlyrics), but the Git repository isn't the documentation page. Can we recover the official documentation page? If I guess well there is no hosting, just a domain. Could it be a solution Github Pages?
