### ISSUE TITLE
Add new author type "Words and Music"

### ISSUE THREAD

**Issue by gyuris** [openlyrics/openlyrics#57]
This topic appeared first time on [OpenLyrics Google group](https://groups.google.com/g/openlyrics/c/kBTOFB6WtJA). After that OpenLP has implemented it as [`words+music`](https://gitlab.com/openlp/openlp/-/blob/master/openlp/plugins/songs/lib/db.py#L58).

Lets standardise this author type for convenience.

#### 1st mode: `words+music`

Standardize the way as it is implemented:

```
<author type="words+music">Chris Tomlin</author>
```

Advantages:
- Implemented in OpenLP

Disadvantages
- Ugly

#### 2nd mode: list

In current design we add an author as many time as he did something for the song. It would be very clear to enumerate each author only one time and create a list for author types. (See #39)

 ```
<author type="words">Joel Houston</author>
<author type="words music">Chris Tomlin</author>
<author type="word music translation">Kari Jobe</author>
<author type="translation variant">Csiszér László</author>
```

Advantages:
- It's beautiful and simple.

Disadvantages
- Currently `translation` type requires an additional `lang` attribute. It could be omitted because we can mark the document language (#32) and normally the translator is mentioned only in OpenLyrics document which contains translated lyrics. So it seems unnecessary. But there are multilingual OpenLyrics and in these cases it makes sense to indicate who translated it into which language.

Tasks:
- [x] RelaxNG
- [x] Documentation + Changelog
- [x] Reference implementation: XSL, CSS
- [x] 0.8 to 0.9 XSL converter
- [x] 0.9 to 0.8 XSL converter

**Comment by gyuris** [comment]
Let's think about this together with #39.

We have to think of three type of authors:

1) Original author of the song: _composer_, who writes the **music** and _lyricist_ or _poet_, who writes **words**.
2) _Arranger_ (alterer, altered by): who produces an alternate version, **arrangement** of song, who rewrites, alters, reworks a song or adopts a song to another language (changing a little bit the music and the words).
3) _Translator_, who creates a new **translation**.

Based on the above I suggest these author types:

```xml
<author type="music">Chris Tomlin</author>
<author type="words">Joel Houston</author>
<author type="translation" lang="hu">Csiszér László</author>
<author type="arrangement">Kari Jobe</author>
```
Last type may be `variant` or `alternation` or `adaptation`.

The question is: How to combine them? There are 4+6+4+1 logical combination. From this 15 combination the real cases are:

1.  `music`
2.  `words`
3.  `translation`
4.  `arrangement` (and this case can be marked as a `variant`)
5.  `music`+`words` (as in OpenLP)
6.  `music`+`translation`: for example when a bilingual author writes a song in English and Spanish.
7.  ~~`music`+`arrangement`~~: that is the original author, this this case should be simple `music` and a new `version`.
8.  `words`+`translation`: as 6
9.  ~~`words`+`arrangement`~~: as 7 → `words` (2) and a new `version`.
10.  `translation`+`arrangement`: when a translator creates an adoption (this case can be marked as a `variant`)
11. `music`+`words`+`translation`: as 6
12. ~~`music`+`words`+`arrangement`~~: as 7 → `music`+`words` (5) and a new `version`
13. ~~`music`+`translation`+`arrangement`~~: as 7 → `music`+`translation` (6) and a new `version`
14. ~~`words`+`translation`+`arrangement`~~: as 7 →`words`+`translation` (8) and a new `version`
15. ~~`music`+`words`+`translation`+`arrangement`~~: as 7 → `music`+`words`+`translation` (11) and a new `version`

So this 9 case are in a real word:
*  `music`
*  `words`
*  `translation`
*  `arrangement`
*  `music`+`words`
*  `music`+`translation`
*  `words`+`translation`
*  `translation`+`arrangement`
*  `music`+`words`+`translation`

And an important design aspect: `translation` type needs a further `lang` attribute.

### Version A.: Enumerate persons several times (aka 0.8)

```xml
<author type="music">Chris Tomlin</author>
<author type="words">Chris Tomlin</author>
<author type="translation" lang="hu">Csiszér László</author>
<author type="arrangement">Csiszér László</author>
<author type="words">Kari Jobe</author>
<author type="music">Kari Jobe</author>
<author type="translation" lang="es">Kari Jobe</author>
```
Pro:

- It is clear that language refers only to translation.
- OpenLP has an internal `words+music` type, but on export it [exports separately](https://gitlab.com/openlp/openlp/-/blob/master/openlp/plugins/songs/lib/openlyricsxml.py#L265). 

Against:

- Verbose.
- Client must join authors as OpenLP does.

### Version B.: Enumerate persons only one time and create mixed types (aka OpenLP internal)

```xml
<author type="words+music">Chris Tomlin</author>
<author type="arrangement+translation">Csiszér László</author>
<author type="words+music+translation">Kari Jobe</author>
```
This is generally what O[penLP introduces internally](https://gitlab.com/openlp/openlp/-/blob/master/openlp/plugins/songs/lib/db.py#L53) with `words+music` type.

Pro:
- ?

Against:
- We must define 9 combination type.
- Ugly. I have never seen such values in the XML world.

### Version C.: Enumerate persons only one time with a list (like `class` in HTML)

```xml
<author type="words music">Chris Tomlin</author>
<author type="arrangement translation">Csiszér László</author>
<author type="words music translation">Kari Jobe</author>
<author type="translation" lang="ro">Laslo Ungurean</author>
```
Pro:
- Shorthand version alongside normal.
- It is not prohibited to write separately (`<author type="words">Chris Tomlin</author><author type="music">Chris Tomlin</author>`).
- There is no need to define 9 version, this is a simple list (`list` + `oneOrMore` + `choice`)

Against:
- It's not clear what the `"lang"` attribute applies to... My thought: Since we now have a default language (`<song xml:lang="">`) we can remove the 'mandatory' flag from `translation` type. If it is not declared it means that translation for **current, defualt** language. (Attention: OpenLP currently provides invalid OpenLyrics because it is impossible to set translation language in OpenLP.) In bilingual OpenLyrics documents where it is important to set the language the `translation` type cannot be mixed with other types. That's what I mean:

```xml
<define name="authors">
  <element name="authors">
    <oneOrMore>
      <element name="author">
        <ref name="nonEmptyContent"/>
        <optional>
          <choice>
            <attribute name="type">
              <list>
                <oneOrMore>
                  <choice>
                    <value>music</value>
                    <value>words</value>
                    <value>translation</value>
                    <value>arrangement</value>
                  </choice>
                </oneOrMore>
              </list>
            </attribute>
            <!-- when attrib 'type' value is 'translation' and needs an attribute 'lang'.
                 'xml:lang' can't be used. xml:lang means in what language is the
                 content of an element and this is not the case. -->
            <group>
              <attribute name="type">
                <value>translation</value>
              </attribute>
              <optional>
                <ref name="langAttribute"/>
              </optional>
            </group>
          </choice>
        </optional>
      </element>
    </oneOrMore>
  </element>
</define>
```

These are valid types:

```xml
<author type="arrangement music words translation">Gellért Gyuris</author>
<author type="translation" lang="hu">Gellért Gyuris</author>
<author type="translation">Gellért Gyuris</author>
```

But that is invalid:

```xml
<author type="arrangement music words translation" lang="hu">Gellért Gyuris</author>
```

### Summary

- I suggest to add a new type: `type="arrangement"` (or `variant`, `alternation`, `adaptation`).
- I suggest to remove mandatory flag from `type="translation"`. Arguments above.
- I suggest to ignore variant B) for OpenLyrics standard. It does not affect OpenLP's internal implementation. It is OK, it exports valid OpenLyrics.
- I suggest to use variant A) or even more C). Variant C) has advantages.

**Comment by matysek** [comment]
My suggestion is to do the following:
- variant A
- add a new 'arrangement'
- make 'lang' in 'translation' optional
