### ISSUE TITLE
Don't break OpenLP's new verse names

### ISSUE THREAD

**Issue by gyuris** [openlyrics/openlyrics#66]
I just realised that in the meanwhile OpenLP (3) has differed from OpenLyrics 0.8 in its implementation of verse types and names. I think it is an important aspect to don't break OpenLP and OpenLyrics files created in OpenLP. I suggest to modify our current (unfinished)  0.9 version.

## Current state

In OpenLyrics 0.8 there was 5 verse types, but OpenLP added two other types: intro (i), and other (o). See the tables below. The problem is that:
- intro (i) is in conflict with OpenLyrics 0.9 *instrumental* verse type "intro (i)",
- the "o" abbreviation is in conflict with OpenLyrics 0.9 *instrumental* verse type outro's abbreviation ("o").

### OpenLyrics 0.8

See https://github.com/openlyrics/openlyrics/blob/v0.8/docs/source/dataformat.rst

short | name
-- | --
v | verse
c | chorus
p | pre-chorus
b | bridge
e | ending

### OpenLP 3
short | name
-- | --
v | verse
c | chorus
p | pre-chorus
b | bridge
e | ending
**i** | **intro**
**o** | **other**

### OpenLyrics 0.9

See: https://github.com/openlyrics/openlyrics/blob/master/docs/source/dataformat.rst

type | short | name
-- | -- | --
verse | v | verse
verse | c | chorus
verse | p | pre-chorus
verse | b | bridge
verse | e | ending
instrument | **i** | **intro**
instrument | m | middle
instrument | **o** | outro
instrument | s | solo

## Proposal

I can imagine two solutions:

### Proposal A.: Find new verse names and abbreviations for OL 0.9

type | short | name
-- | -- | --
verse | v | verse
verse | c | chorus
verse | p | pre-chorus
verse | b | bridge
verse | e | ending
verse | i | intro
verse | o | other
instrument | n | instrumental intro
instrument | m | instrumental middle
instrument | u | instrumental outro
instrument | s | instrumental solo

It this case we must abandon the principle that the abbreviation is the first letter:
- instrumental intro (n)
- instrumental outro (u)

### Proposal B: Mix instrument and verse types

type | short | name
-- | -- | --
verse | v | verse
verse | c | chorus
verse | p | pre-chorus
verse | b | bridge
verse | o | other
verse/instrument | i | intro
verse/instrument | e | ending
instrument | s | solo
instrument | m | middle

In this case these tags are valid:

```
<verse name="i1">[intro with lyrics and chords]</verse>
<instrument name="i2">[only instrumental intro]</instrument>
```

This proposal introduces "intro" and "ending / outro" as verse _or_ instrumental. In this case we can preserve the principle that the abbreviation is the first letter. It is backwards compatible: we don't need an upgrade script from 0.8 to 0.9  (or OpenLP to 0.9) because all old sections are supported in 0.9.

### +1 to consider

If we need more parts it is to time to introduce them, for example:
- down chorus (verse)
- down verse (verse)
- post-chorus (verse)
- hook (instrument)
- riff (instrument)
- tag (instrument)

# My opinion

- I prefer proposal B.
- @matysek, @rsnyman please, comment. I look forward to your opinions. You are free to make new proposal.

# Tasks:
- [x] RelaxNG:
- [x] Documentation + Changelog
- [x] Reference implementation (XSL, CSS)
- 0.8 to 0.9 XSL converter
- 0.9 to 0.8 XSL converter

**Comment by matysek** [comment]
Hi @gyuris, @rsnyman I prefer proposal B. I do not think we need more parts at the moment.

**Comment by matysek** [comment]
@gyuris Thank you for your effort.
