### ISSUE TITLE
Restrict transposition between -11 and 11

### ISSUE THREAD

**Issue by gyuris** [openlyrics/openlyrics#70]
Currently the value for transposition can be between -99 and 99. But it makes no musical sense above 11.

I suggest to restrict values:
```xml
  <define name="transposition">
    <element name="transposition">
      <data type="integer">
        <param name="minInclusive">-11</param>
        <param name="maxInclusive">11</param>
      </data>
    </element>
  </define>
```

This change should be taken into account during the 0.8 to 0.9 conversion.

Tasks:
- [x] RelaxNG:
- [x] Documentation + Changelog
- Reference implementation: XSL, CSS  (no changes needed)
- [x] 0.8 to 0.9 XSL converter
- 0.9 to 0.8 XSL converter (no changes needed)

**Comment by matysek** [comment]
Yes, it makes absolutely sense.
