### ISSUE TITLE
Add time signature

### ISSUE THREAD

**Issue by gyuris** [openlyrics/openlyrics#71]
Time signature is originally discussed in this tread: https://groups.google.com/g/openlyrics/c/fZTlOQBihpE/m/2OGgx2XzyNsJ

I suggest to standardize in this way: 

```xml
<element name="signature">
  <data type="token">
    <param name="pattern">(6[0-3]|[1-5][0-9]|[1-9])/(64|32|16|8|4|2|1)</param>
  </data>
</element>
```
- Element name: `signature`. References: OpenSong: `time_sig`, OnSong: `time`, MusisXML: `time`. Other possible tag names: `time`, `timesignature`,  `timeSignature`.  Comments are welcome!  If `timesignature` is the preferred tag name as suggested by the community, I  recomment to use `timeSignature` to be consistent with `ccliNo` and `verseOrder`. 
- Possible values: number between 1 and 63 + "/" + one of these numbers: 1, 2, 4, 8, 16, 32, 64. Examples: 4/4, 3/4, 2/4, 6/8
- Example: `<signature>3/4</signature>`.

Tasks:
- [x] RelaxNG:
- [x] Documentation + Changelog
- [x] Reference implementation: XSL, CSS
- 0.8 to 0.9 XSL converter (no changes needed)
- [x] 0.9 to 0.8 XSL converter: to remove

**Comment by matysek** [comment]
@gyuris I prefer 'timeSignature' and agree with the possible values and pattern for it. Thank you!
