### ISSUE TITLE
Component is too 'greedy'

### ISSUE THREAD

**Issue by stuerp** [openlyrics/openlyrics#81]
When you edit the lyrics using the properties dialog (not via the Open Lyrics panel) of tracks that are NOT playing while another track IS playing all the edits are not saved (or overwritten by foo_openlyrics, difficult too tell).

**Comment by gyuris** [comment]
@stuerp, which software is this?

This is general openlyrics standard repository...

**Comment by stuerp** [comment]
My bad, I meant to post to foo_openlyrics. Sorry for the confusion.
